import { SearchResultObj } from "./customTypes";

export const DUMMY_RESULTS: SearchResultObj[] = [
  {
    product_url: "ratemyresume.ai",
    product_name: "Rate My Resume",
    product_description:
      "RateMyResume.ai provides personalized, AI-driven feedback to optimize your resume, helping you stand out in the job market and advance your career goals efficiently.",
    product_image_file_name: "ratemyresume-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/rate-my-resume",
    ph_listed_at: "2024-05-15T10:14:36.358Z",
    ph_updated_at: "2024-05-15T10:14:36.358Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "en.macromicro.me",
    product_name: "MacroMicro",
    product_description:
      "MacroMicro is committed to consolidating global economic data, while deploying technology to efficiently discover the clues to economic cycles. \nWe believe that no investment decision should be taken without the consideration of economic fundamentals.\nMacroMicro is changing the way people invest by providing sophisticated fundamental analysis as well as empowering investors to have more control over their investment decisions.',",
    product_image_file_name: "en-d-macromicro-d-me.png",
    ph_source_url: "https://www.producthunt.com/products/macromicro",
    ph_listed_at: "2024-05-14T21:50:20.182Z",
    ph_updated_at: "2024-05-14T21:50:20.182Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/macromicro.me/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/MacroMicroMe",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://www.youtube.com/channel/UC9orjX1KFXp1iJ8_TGEWpyA",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "lemmilink.fr",
    product_name: "LemmiLink",
    product_description:
      "Lemmilink: Elevate your SEO easily. - Buy/sell quality backlinks - User-friendly interface - Top-ranked page links - Rigorous source vetting - Transparent pricing - Ongoing link monitoring - Affiliate program - Enhanced SEO benefits - Responsive support",
    product_image_file_name: "lemmilink-d-fr.gif",
    ph_source_url: "https://www.producthunt.com/products/lemmilink",
    ph_listed_at: "2024-05-12T11:33:07.713Z",
    ph_updated_at: "2024-05-12T11:33:07.713Z",
    sm_email: "contact@lemmilink.com",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "simplifiediq.com",
    product_name: "SimplifiedIQ",
    product_description:
      "Save time and resources by automatically creating and grading customized assessments tailored to your training delivery with our data-driven solution that helps you gain the right insights to make informed decisions.",
    product_image_file_name: "simplifiediq-d-com.jpg",
    ph_source_url: "https://www.producthunt.com/products/simplifiediq",
    ph_listed_at: "2024-05-11T17:38:08.819Z",
    ph_updated_at: "2024-05-11T17:38:08.819Z",
    sm_email: "contact@mysite.com",
    sm_instagram: "http://www.instagram.com/_simplifiediq",
    sm_facebook: "https://www.facebook.com/Simplifiediq/",
    sm_twitter: "http://www.twitter.com/_simplifiediq",
    sm_discord: null,
    sm_linkedin: "http://www.linkedin.com/company/simplifiediq",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "voicenotes.com",
    product_name: "Voicenotes",
    product_description:
      "Voicenotes is an intelligent note-taking app. Record your thoughts freely, get them transcribed using state-of-the-art AI, and ask about every word you spoke.",
    product_image_file_name: "voicenotes-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/voicenotes",
    ph_listed_at: "2024-05-11T14:32:12.663Z",
    ph_updated_at: "2024-05-11T14:32:12.663Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "thefounderspress.com",
    product_name: "FoundersPress",
    product_description:
      "The FoundersPress covers startup news and tech across the globe, connecting you with the latest stories in startups, venture capital, innovation, and more.",
    product_image_file_name: "thefounderspress-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/founderspress",
    ph_listed_at: "2024-05-09T20:00:16.046Z",
    ph_updated_at: "2024-05-09T20:00:16.046Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/founderspress/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/FoundersPress",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/founders-press/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "hyperbooth.ai",
    product_name: "Hyperbooth",
    product_description:
      "HyperBooth.Ai is one of the world's highest quality and fastest AI-powered personalized photo generators. Simply upload only one input photo to generate AI photos of your preferred style in 30 seconds or less!",
    product_image_file_name: "hyperbooth-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/hyperbooth",
    ph_listed_at: "2024-05-07T01:02:52.430Z",
    ph_updated_at: "2024-05-07T01:02:52.430Z",
    sm_email: "support@hyperbooth.ai",
    sm_instagram: "https://www.instagram.com/hyperbooth_ai/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/HyperBooth_AI",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://www.youtube.com/channel/UCnZRR8XCm50FRhdrEmcSwfA",
    sm_tiktok: "https://www.tiktok.com/@hyperbooth_ai",
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "worgit.ai",
    product_name: "Worgit",
    product_description:
      "Worgit.ai enhances business productivity by offering over 150 AI-driven tools and templates for automating essential business tasks, including marketing, HR, legal, and financial processes.",
    product_image_file_name: "worgit-d-ai.webp",
    ph_source_url: "https://www.producthunt.com/products/worgit",
    ph_listed_at: "2024-05-07T00:32:37.997Z",
    ph_updated_at: "2024-05-07T00:32:37.997Z",
    sm_email: "info@worgit.ai",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "fontviz.app",
    product_name: "FontViz",
    product_description:
      "FontViz simplifies font inspection on web apps. Features include one-click font inspection, text highlighting, comparison, & HTML tag SEO checks. Perfect web typography effortlessly. Want to know font, color or weight info? Download FontViz for quick insights!",
    product_image_file_name: "fontviz-d-app.png",
    ph_source_url: "https://www.producthunt.com/products/fontviz",
    ph_listed_at: "2024-05-03T08:17:13.752Z",
    ph_updated_at: "2024-05-03T08:17:13.752Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/14630975",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "wife.app",
    product_name: "WifeAPP",
    product_description:
      "Chat and video with AI GirlFriend, who is always friendly with you. Ask her to send a photo or make a video and be surprised by the results. 🚀 Choose a ready-made avatar or create a unique one based on your photos, voice and preferences.",
    product_image_file_name: "wife-d-app.png",
    ph_source_url: "https://www.producthunt.com/products/wifeapp",
    ph_listed_at: "2024-05-03T03:56:05.004Z",
    ph_updated_at: "2024-05-03T03:56:05.004Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/wifeonline",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "fiskl.com",
    product_name: "FISKL",
    product_description:
      "AI-powered Accounting with end-to-end Stripe integration and reconciliation. Built for global businesses, offering multi-currency accounting and invoicing, payments, automated sync with 21k banks worldwide, tax tracking and more.",
    product_image_file_name: "fiskl-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/fiskl",
    ph_listed_at: "2024-05-03T03:50:03.207Z",
    ph_updated_at: "2024-05-03T03:50:03.207Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/FisklApp/",
    sm_twitter: "https://twitter.com/FisklApp",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/fiskl-limited/",
    sm_youtube: "https://www.youtube.com/channel/UCL1LEvSYp2uIo5sAg68ZKRw",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "boodlebox.ai",
    product_name: "BoodleBox",
    product_description:
      "The simplest, most secure AI collaboration platform with top AI tools – ChatGPT, Claude, Gemini, Llama, Perplexity, SDXL, DALLE – and 1,000+ custom GPTs. Make better decisions, personalize results, and cut costs when your team, AIs, and docs work together.",
    product_image_file_name: "boodlebox-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/boodlebox",
    ph_listed_at: "2024-05-02T10:03:50.444Z",
    ph_updated_at: "2024-05-02T10:03:50.444Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/boodleAI",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/boodleai/",
    sm_youtube: "https://www.youtube.com/@boodleAI",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "autoface.io",
    product_name: "Autoface",
    product_description:
      "Unleash Earning Power Effortlessly Scale your business with multiple Facebook accounts in just a few minutes. Effortlessly expand your business and save substantial time and money, all through the convenience of your computer.",
    product_image_file_name: "autoface-d-io.ico",
    ph_source_url: "https://www.producthunt.com/products/autoface",
    ph_listed_at: "2024-05-01T19:47:03.490Z",
    ph_updated_at: "2024-05-01T19:47:03.490Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "professorai.co",
    product_name: "ProfessorAI",
    product_description:
      "ProfessorAI is the personalized AI tutor for standardized tests. Our startup addresses the issues of expensive tutors, limited time with teachers, and ineffective comprehension of course material through a custom chatbot and library system to help students perform better in AP classes.",
    product_image_file_name: "professorai-d-co.png",
    ph_source_url: "https://www.producthunt.com/products/professorai-2",
    ph_listed_at: "2024-04-24T23:40:20.277Z",
    ph_updated_at: "2024-04-24T23:40:20.277Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/professorai.co/",
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/professorai/",
    sm_youtube: "https://www.youtube.com/c/GuinnessAndMathGuy",
    sm_tiktok: "https://www.tiktok.com/@actual.education",
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "coffeespace.com",
    product_name: "CoffeeSpace",
    product_description:
      "CoffeeSpace is the platform to find cofounders or someone to explore your startup or business idea with. It’s a platform connecting like-minded entrepreneurs, offering a supportive space where great ideas meet great people.",
    product_image_file_name: "coffeespace-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/coffeespace",
    ph_listed_at: "2024-04-23T01:38:16.718Z",
    ph_updated_at: "2024-04-23T01:38:16.718Z",
    sm_email: "contact@coffeespace.com",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://x.com/coffeespaceapp",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/coffeespace-inc/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "app.hoggo.io",
    product_name: "hoggo",
    product_description:
      "Trust Hub streamlines privacy and security assessments for software buyers and sellers, making B2B transactions faster, safer, and more trustworthy. Evaluate third parties, demonstrate compliance, and gain a competitive edge without breaking a sweat.\n\n🦾 With our AI-driven transparency, we generate your company's Passport & Trust Grade and enable you to effortlessly demonstrate and improve your organization's security and privacy posture.",
    product_image_file_name: "app-d-hoggo-d-io.gif",
    ph_source_url: "https://www.producthunt.com/products/trust-hub-by-hoggo",
    ph_listed_at: "2024-04-20T12:35:48.547Z",
    ph_updated_at: "2024-04-20T12:35:48.547Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "optimateai.com",
    product_name: "OptimateAI",
    product_description:
      "OptimateAI has all of your sales operations in one place. Get paid fast by providing multiple payment options to collect online payments, track sales KPI’s, automate accounts receivables & pay commissions in just 2-clicks.",
    product_image_file_name: "optimateai-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/optimateai",
    ph_listed_at: "2024-04-17T13:05:56.962Z",
    ph_updated_at: "2024-04-17T13:05:56.962Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/optimateai/",
    sm_youtube: "https://www.youtube.com/@optimateai",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "pixcleaner.com/change-background",
    product_name: "pixcleaner change background AI",
    product_description:
      "Remove backgrounds and enhance your product images with our AI-powered background remover. Our professional editing services will help you boost your sales and customer satisfaction. Try it now.",
    product_image_file_name: "pixcleaner-d-com-s-change-background.png",
    ph_source_url:
      "https://www.producthunt.com/products/pixcleaner-change-background-ai",
    ph_listed_at: "2024-04-17T04:52:11.749Z",
    ph_updated_at: "2024-04-17T04:52:11.749Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "prometai.app",
    product_name: "PrometAI",
    product_description:
      "PrometAI is an AI-powered, data-enriched, and framework-oriented tool that specializes in creating business plans and valuations. It is tailored for the needs of early-stage SME founders, facilitating the generation",
    product_image_file_name: "prometai-d-app.png",
    ph_source_url: "https://www.producthunt.com/products/prometai",
    ph_listed_at: "2024-04-17T02:06:18.470Z",
    ph_updated_at: "2024-04-17T02:06:18.470Z",
    sm_email: "info@prometai.app",
    sm_instagram: "https://www.instagram.com/prometai.app/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/PrometAI",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/prometai/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "sweego.io",
    product_name: "Sweego",
    product_description:
      "Sweego is a European solution for developers that lets you send notifications easily while keeping control over your data and your environnemental impact. We're working on adding new channels in addition to email : SMS, Slack, RCS, in-app notifications...",
    product_image_file_name: "sweego-d-io.png",
    ph_source_url: "https://www.producthunt.com/products/sweego",
    ph_listed_at: "2024-04-16T07:10:08.263Z",
    ph_updated_at: "2024-04-16T07:10:08.263Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/Sweego_io/",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/sweego-io/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "nexa.org",
    product_name: "Nexa: Peer-2-Peer Digital Value System",
    product_description:
      "Next-generation UTXO Layer 1 blockchain with instant transactions, smart contracts and tokens. Adopting most recent technologies to proven basis UTXO network. Just like Bitcoin - Nexa is equivalent of energy and being used as store of value, and as native Nexa blockchain coin. We have the very same tokenomics and halvings each and every 1,050,000 blocks and halving rewards being cut in the half. Use it for gas, liquidity providing, developing and much more.",
    product_image_file_name: "nexa-d-org.png",
    ph_source_url: "https://www.producthunt.com/products/nexa-2",
    ph_listed_at: "2024-04-16T03:58:40.492Z",
    ph_updated_at: "2024-04-16T03:58:40.492Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/nexamoney",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://www.youtube.com/@NexaCoin",
    sm_tiktok: null,
    sm_reddit: "https://www.reddit.com/r/Nexa/",
    popularity: "high",
  },
  {
    product_url: "sms-activate.org",
    product_name: "SMS-Activate",
    product_description:
      "SMS-Activate is a service for sale and rent of virtual numbers of more than 180 countries. We provide virtual numbers in most countries of the world so that you can use them to receive an SMS with a confirmation code online.",
    product_image_file_name: "sms-activate-d-org.png",
    ph_source_url: "https://www.producthunt.com/products/sms-activate",
    ph_listed_at: "2024-04-13T05:18:31.187Z",
    ph_updated_at: "2024-04-13T05:18:31.187Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/smsactivateorg",
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://www.youtube.com/@sms-activateen-virtualnumb1359",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "product.supertone.ai/shift",
    product_name: "Supertone Shift",
    product_description:
      "Supertone Shift is a real-time voice changer serviced as a desktop application. With minimal latency and hyper-realistic voice quality, it allows users to immediately switch to any selected voice.",
    product_image_file_name: "product-d-supertone-d-ai-s-shift.ico",
    ph_source_url: "https://www.producthunt.com/products/supertone-shift",
    ph_listed_at: "2024-04-10T18:37:48.236Z",
    ph_updated_at: "2024-04-10T18:37:48.236Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "app.hidoc.co",
    product_name: "Hidoc Bot",
    product_description:
      "Hidoc Dr is a healthcare-focused online learning platform which provides a common platform to various specialties with a focus to break the boundary barriers.\nEducation never ends for a doctor, Hidoc Dr takes medical education at the doorstep and let a doctor learn on the go without quitting their clinical practice. We let a doctor enhance their clinical skills and let them gain specialized in-depth knowledge.\nPowered by artificial intelligence, we have an online collection of latest journal articles, drug database, disease database, drug interaction checker, quizzes, surveys, and medical calculators.\nAs a medical professional, you must continuously demonstrate you are staying up-to-date with the latest evidence and best practices which can be successfully achieved here at Hidoc Dr",
    product_image_file_name: "app-d-hidoc-d-co.png",
    ph_source_url: "https://www.producthunt.com/products/hidoc-bot",
    ph_listed_at: "2024-04-08T00:36:26.638Z",
    ph_updated_at: "2024-04-08T00:36:26.638Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "chatsweetie.com",
    product_name: "ChatSweetie - Free NSFW AI Chat Online",
    product_description:
      "With ChatSweetie porn chatbot, you can chat online with your chosen virtual character anytime, anywhere, and even develop a companionship. We offer you connections beyond the limitations of the physical world.",
    product_image_file_name: "chatsweetie-d-com.png",
    ph_source_url:
      "https://www.producthunt.com/products/chatsweetie-free-nsfw-ai-chat-online",
    ph_listed_at: "2024-04-07T18:07:42.001Z",
    ph_updated_at: "2024-04-07T18:07:42.001Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/ChatSweetie_com",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "justahost.cloud",
    product_name: "JustAHost",
    product_description:
      "Unlock digital success with JustAHost: the ultimate solution for new entrepreneurs. Empower your website dreams at minimum cost. Go limitless, go JustAHost.",
    product_image_file_name: "justahost-d-cloud.png",
    ph_source_url: "https://www.producthunt.com/products/justahost",
    ph_listed_at: "2024-04-07T10:38:18.289Z",
    ph_updated_at: "2024-04-07T10:38:18.289Z",
    sm_email: "support@justahost.cloud",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/justahostcloud/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "speedlegal.io",
    product_name: "SpeedLegal",
    product_description:
      "SpeedLegal is an AI tool that helps you understand and negotiate contracts better. It can quickly identify potential risks and explain complicated legal terms in simple language. SpeedLegal also gives you personalized suggestions to improve your contract.",
    product_image_file_name: "speedlegal-d-io.png",
    ph_source_url: "https://www.producthunt.com/products/speedlegal",
    ph_listed_at: "2024-04-06T12:58:05.213Z",
    ph_updated_at: "2024-04-06T12:58:05.213Z",
    sm_email: "hello@speedlegal.io?subject=Interested%20in%20SpeedLegal%20demo",
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/speedlegalai",
    sm_twitter: "https://twitter.com/speedlegalinc",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/speedlegal/",
    sm_youtube:
      "https://www.youtube.com/channel/UCYqd5azREZ9e0_2iWGEu9NA/featured",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "neon.tech",
    product_name: "Neon",
    product_description:
      "Neon reimagines Postgres with a serverless architecture. With a generous free tier, scale-to-zero, and true database branching. Copy data and schema in a second and scale resources automatically. Ideal for developers prioritizing scalability and performance.",
    product_image_file_name: "neon-d-tech.png",
    ph_source_url: "https://www.producthunt.com/products/neon-6",
    ph_listed_at: "2024-04-05T18:04:02.852Z",
    ph_updated_at: "2024-04-05T18:04:02.852Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/neondatabase/",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/neon-inc/",
    sm_youtube: "https://www.youtube.com/channel/UCoMzQTJSIr7-RU1QbomQI2w",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "wallpea.com",
    product_name: "Wallpea",
    product_description:
      "Wallpea plays a crucial role in revolutionizing the stock image industry by providing millions of businesses, designers, writers, artists, programmers, and other creators with access to a vast array of AI generated stunning images that they can freely use.",
    product_image_file_name: "wallpea-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/wallpea",
    ph_listed_at: "2024-04-05T08:30:45.659Z",
    ph_updated_at: "2024-04-05T08:30:45.659Z",
    sm_email: "folrry@wallpea.com",
    sm_instagram: "https://www.instagram.com/wallpeastock/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/wallpeastock/",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
  {
    product_url: "leads-sniper.com",
    product_name: "Leads Sniper",
    product_description:
      "Leads Sniper offers an array of web scraping tools for Google Maps, Google Search, Yellow Pages, and domains empowering businesses to scrape valuable leads and essential contact information like emails and more.",
    product_image_file_name: "leads-sniper-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/leads-sniper",
    ph_listed_at: "2024-04-05T07:10:05.666Z",
    ph_updated_at: "2024-04-05T07:10:05.666Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/profile.php?id=100088569354110",
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://www.youtube.com/@leads-sniper",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "talentprotocol.com",
    product_name: "Talent Protocol",
    product_description:
      "Talent Protocol is building the resume for the onchain era of the internet. The protocol works with trusted data sources like GitHub, Farcaster or LinkedIn to unlock unique reputation data and bring it onchain as verifiable and interoperable credentials.",
    product_image_file_name: "talentprotocol-d-com.jpg",
    ph_source_url: "https://www.producthunt.com/products/talent-protocol",
    ph_listed_at: "2024-04-04T12:38:50.857Z",
    ph_updated_at: "2024-04-04T12:38:50.857Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/TalentProtocol",
    sm_discord: "https://discord.com/invite/talentprotocol",
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "modeliks.com",
    product_name: "Modeliks",
    product_description:
      "Modeliks is a business planning and investor reporting software for startups and SMEs. It helps the user build a professional financial model, report to investors with automated dashboards and create an investor ready pitch deck or business plan.",
    product_image_file_name: "modeliks-d-com.ico",
    ph_source_url: "https://www.producthunt.com/products/modeliks",
    ph_listed_at: "2024-04-04T02:55:54.485Z",
    ph_updated_at: "2024-04-04T02:55:54.485Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "goprofiles.io",
    product_name: "GoProfiles",
    product_description:
      "A hub for your team to find shared connections, celebrate wins, and boost company culture. We combined the best parts of employee directories and peer recognition to build a totally new kind of people platform — powered by generative AI!",
    product_image_file_name: "goprofiles-d-io.png",
    ph_source_url: "https://www.producthunt.com/products/goprofiles",
    ph_listed_at: "2024-04-01T08:20:55.581Z",
    ph_updated_at: "2024-04-01T08:20:55.581Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/goprofiles.io",
    sm_facebook: "https://www.facebook.com/GoProfiles.io",
    sm_twitter: "https://www.twitter.com/GoProfiles_io",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: "https://www.youtube.com/@GoProfiles_io",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "climatize.earth",
    product_name: "Climatize",
    product_description:
      "Climatize is an SEC-registered platform for renewable energy investments, offering high-yield returns of 8-10% in under a year. Invest in community solar and solar storage to become a stakeholder in the energy transition.",
    product_image_file_name: "climatize-d-earth.webp",
    ph_source_url: "https://www.producthunt.com/products/climatize",
    ph_listed_at: "2024-03-31T18:48:07.311Z",
    ph_updated_at: "2024-03-31T18:48:07.311Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/climatize.earth/",
    sm_facebook: "https://www.facebook.com/climatize.earth",
    sm_twitter: "https://mobile.twitter.com/Climatize_earth",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/climatize-earth/",
    sm_youtube: "https://www.youtube.com/channel/UCuSeK0a8ilhHLfw6qGiQKBQ",
    sm_tiktok: "https://www.tiktok.com/@climatize.earth",
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "larq.ai",
    product_name: "LARQ",
    product_description:
      "Learning aptitude retention quizzes is the first AI quiz generator tool that works during live meeting sessions as well as with pre recorded video and PDF.",
    product_image_file_name: "larq-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/larq-2",
    ph_listed_at: "2024-03-26T05:52:45.117Z",
    ph_updated_at: "2024-03-26T05:52:45.117Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "worklenz.com",
    product_name: "Worklenz",
    product_description:
      "Unleash clarity and collaboration with Worklenz! Our platform streamlines workflows, empowering teams to work together seamlessly. Simplify task management, optimize resource allocation, gain valuable insights, and guide your team to success.",
    product_image_file_name: "worklenz-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/worklenz",
    ph_listed_at: "2024-03-23T23:39:09.752Z",
    ph_updated_at: "2024-03-23T23:39:09.752Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/Worklenz/",
    sm_twitter: "https://twitter.com/WorklenzHQ",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "anthropic.com/claude",
    product_name: "Claude by Anthropic",
    product_description:
      "A family of models that offer the best combination of speed and performance for enterprise use cases, at a lower cost than other models on the market.",
    product_image_file_name: "anthropic-d-com-s-claude.png",
    ph_source_url: "https://www.producthunt.com/products/claude",
    ph_listed_at: "2024-03-22T16:14:17.992Z",
    ph_updated_at: "2024-03-22T16:14:17.992Z",
    sm_email: "press@anthropic.com",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/AnthropicAI",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/anthropicresearch",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "macula.link",
    product_name: "Macula",
    product_description:
      "Macula is a command center for managing all your multimedia content without compromising on ownership and attribution. Securely store, share across the internet, monitor usage & analyze performance.",
    product_image_file_name: "macula-d-link.ico",
    ph_source_url: "https://www.producthunt.com/products/macula",
    ph_listed_at: "2024-03-20T10:46:18.068Z",
    ph_updated_at: "2024-03-20T10:46:18.068Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/Macula_link",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "biliki.ai",
    product_name: "Biliki AI",
    product_description:
      "Avoid time consuming process, Get personalized itinerary suggestions, discover eco-friendly accommodations, and green travel options to reduce your carbon footprint. Get the best deals on Agoda.com 🚀",
    product_image_file_name: "biliki-d-ai.gif",
    ph_source_url: "https://www.producthunt.com/products/biliki-ai",
    ph_listed_at: "2024-03-20T03:17:55.752Z",
    ph_updated_at: "2024-03-20T03:17:55.752Z",
    sm_email: "info@bilikiapp.com",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "droip.com",
    product_name: "Droip",
    product_description:
      "Droip is a full-fledged no-code website builder for WordPress. Experience granular control over website elements and design any complex layouts. Get a visual no-code editor, an all-encompassing media manager, accessibility tools, interactions, and more.",
    product_image_file_name: "droip-d-com.webp",
    ph_source_url: "https://www.producthunt.com/products/droip",
    ph_listed_at: "2024-03-20T02:31:22.285Z",
    ph_updated_at: "2024-03-20T02:31:22.285Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/DroipNoCode/",
    sm_twitter: "https://x.com/droipNoCode",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/droip/",
    sm_youtube: "https://www.youtube.com/@DroipNoCode",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "usestyle.ai",
    product_name: "Adwin",
    product_description:
      "AI-powered web building, SEO optimization, and Google Ads right at your fingertips, all powered by your personal assistants Crafta, Seona, and Adwin.",
    product_image_file_name: "usestyle-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/adwin",
    ph_listed_at: "2024-03-19T23:55:47.847Z",
    ph_updated_at: "2024-03-19T23:55:47.847Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/usestyle.ai/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/usestyle_ai",
    sm_discord: null,
    sm_linkedin: "http://linkedin.com/company/usestyleai/",
    sm_youtube: "https://www.youtube.com/channel/UCa_9_w-VxuJZzUwd90Rd9dQ",
    sm_tiktok: "https://www.tiktok.com/@usestyle_ai",
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "usestyle.ai/adwin",
    product_name: "Adwin",
    product_description:
      "Reach more customers with automated Google advertising. Adwin's AI platform manages and launches entire Google Ads campaigns, from creating effective campaigns to optimizing keywords to tracking conversion events. Get started with Adwin today.",
    product_image_file_name: "usestyle-d-ai-s-adwin.png",
    ph_source_url: "https://www.producthunt.com/products/adwin",
    ph_listed_at: "2024-03-19T23:55:47.847Z",
    ph_updated_at: "2024-03-19T23:55:47.847Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/usestyle.ai/",
    sm_facebook: null,
    sm_twitter: "https://twitter.com/usestyle_ai",
    sm_discord: null,
    sm_linkedin: "http://linkedin.com/company/usestyleai/",
    sm_youtube: "https://www.youtube.com/channel/UCa_9_w-VxuJZzUwd90Rd9dQ",
    sm_tiktok: "https://www.tiktok.com/@usestyle_ai",
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "rafa.ai",
    product_name: "RAFA",
    product_description:
      "RAFA's AI Agents help you invest like an expert with personalized insights. It’s like having a team of experts, each specializing in one task: Fundamental analysis, Technicals, Momentum, Macro etc, all working together to maximize your portfolio 24/7.",
    product_image_file_name: "rafa-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/rafa-2",
    ph_listed_at: "2024-03-18T20:12:22.540Z",
    ph_updated_at: "2024-03-18T20:12:22.540Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: "https://twitter.com/finance_rafa",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/rafafinanceai/",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "excellent",
  },
  {
    product_url: "tailor.news",
    product_name: "Tailor",
    product_description:
      "Supercharge your news understanding with Tailor! Tailor uses A.I. to summarize, fact-check, and link thousands of articles, podcasts, and YouTube videos. Get digestible, unbiased news stories and podcasts created just for you!",
    product_image_file_name: "tailor-d-news.png",
    ph_source_url:
      "https://www.producthunt.com/products/tailor-42d625d7-785f-43ac-bed5-658ec710e439",
    ph_listed_at: "2024-03-17T00:49:47.749Z",
    ph_updated_at: "2024-03-17T00:49:47.749Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "axur.com",
    product_name: "Polaris",
    product_description:
      "We monitor all the layers of the web, including the Deep and Dark Web, with intensive use of Artificial Intelligence to find and eliminate digital threats",
    product_image_file_name: "axur-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/polaris-2",
    ph_listed_at: "2024-03-15T10:38:18.769Z",
    ph_updated_at: "2024-03-15T10:38:18.769Z",
    sm_email: null,
    sm_instagram: "https://www.instagram.com/axurbr/",
    sm_facebook: "https://www.facebook.com/AxurBrasil/",
    sm_twitter: "https://twitter.com/AxurBrasil/",
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/axur/",
    sm_youtube: "https://www.youtube.com/c/AxurBrasil",
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "musavir.ai",
    product_name: "Musavir.AI",
    product_description:
      "User friendly image generator that creates realistic and stylized images, produces hyper-localized images. Even creates avatars of you, making Musavir.AI your all-in-one solution. Offering enterprises with custom models and team training.",
    product_image_file_name: "musavir-d-ai.png",
    ph_source_url: "https://www.producthunt.com/products/musavir",
    ph_listed_at: "2024-03-13T22:58:27.021Z",
    ph_updated_at: "2024-03-13T22:58:27.021Z",
    sm_email: null,
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "high",
  },
  {
    product_url: "deedsign.com",
    product_name: "DeedSign",
    product_description:
      "DeedSign is a web-based electronic signing platform that replaces conventional paper-based signatures with secure digital ones. It provides an efficient and streamlined method for signing and managing documents, eliminating the reliance on physical paperwork.",
    product_image_file_name: "deedsign-d-com.png",
    ph_source_url: "https://www.producthunt.com/products/deedsign",
    ph_listed_at: "2024-03-13T12:45:03.838Z",
    ph_updated_at: "2024-03-13T12:45:03.838Z",
    sm_email: "support@deedsign.com",
    sm_instagram: null,
    sm_facebook: "https://www.facebook.com/DeedSignHQ",
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: "https://www.linkedin.com/company/deedsign",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "wefaceswap.com",
    product_name: "Wefaceswap",
    product_description:
      "Discover Wefaceswap, a cloud-based faceswap service, where you can effortlessly transform photos, videos, and GIFs with just a few clicks. Experience the ease of realistic faceswapping online.",
    product_image_file_name: "wefaceswap-d-com.ico",
    ph_source_url: "https://www.producthunt.com/products/wefaceswap",
    ph_listed_at: "2024-03-13T02:09:13.481Z",
    ph_updated_at: "2024-03-13T02:09:13.481Z",
    sm_email: "support@wefaceswap.com",
    sm_instagram: "https://www.instagram.com/wefaceswap_ai/",
    sm_facebook: "https://www.facebook.com/wefaceswap/",
    sm_twitter: "https://twitter.com/wefaceswap",
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "katalist.ai",
    product_name: "Katalist AI Storytelling Studio",
    product_description:
      "Katalist is an AI storytelling platform that allows anyone to create engaging visual stories. Enjoy complete control over camera angle, posture, and composition with no AI experience required. With automatic character, scene, and style consistency.",
    product_image_file_name: "katalist-d-ai.png",
    ph_source_url:
      "https://www.producthunt.com/products/katalist-ai-storytelling-studio",
    ph_listed_at: "2024-03-13T01:02:54.157Z",
    ph_updated_at: "2024-03-13T01:02:54.157Z",
    sm_email: "hello@katalist.ai",
    sm_instagram: null,
    sm_facebook: null,
    sm_twitter: null,
    sm_discord: null,
    sm_linkedin: null,
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "very high",
  },
  {
    product_url: "cuelab.app",
    product_name: "CueLab CRM",
    product_description:
      "CueLab CRM is built to help businesses convert more leads into clients and streamline their lead management and CRM. Capture leads from multiple sources, get instant alerts, access contacts, build funnels, strategize follow-up and reach leads faster to close more deals. Boost your sales, build trust and convert leads with prompt response",
    product_image_file_name: "cuelab-d-app.png",
    ph_source_url: "https://www.producthunt.com/products/cuelab-crm",
    ph_listed_at: "2024-03-12T05:49:11.410Z",
    ph_updated_at: "2024-03-12T05:49:11.410Z",
    sm_email: "contact@mysite.com",
    sm_instagram: "https://www.instagram.com/cuelabcrm/",
    sm_facebook: "https://www.facebook.com/CueLabApp?mibextid=ZbWKwL",
    sm_twitter: "https://twitter.com/cuelabcrm",
    sm_discord: null,
    sm_linkedin:
      "https://in.linkedin.com/company/cuelab-crm?trk=public_post_feed-actor-name",
    sm_youtube: null,
    sm_tiktok: null,
    sm_reddit: null,
    popularity: "medium",
  },
];
